#GPIO
# 2 = blue led
# 4 = buzzer
# 13
# 14
# 15 = zRST
# 23 = rx zigbee
# 21 = green led
# 22 = boot
# 19 = tx zigbee
# 25 = scl
# 26 = sda
# 27 = button key
# 33

substitutions:
  devicename: sonoffzbbridgep
  friendly_name: zb-bridge-p

wifi:
  ssid: wifi_ssid
  password: wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: ap_password
  
packages:
  remote-packages:
    url: https://github.com/Giancky79/ZB-Bridge-P
    ref: main
    refresh: 0s
    files: [
      esphome/esphome.yaml,
      esphome/binary_sensor.yaml,
      esphome/light.yaml,
      esphome/output.yaml,
      esphome/rtttl.yaml,
      esphome/sensor.yaml,
      esphome/output.yaml,
      esphome/switch.yaml,
      esphome/text_sensor.yaml,
      esphome/uart.yaml,
      esphome/stream_server.yaml,
   ]  

external_components:
  - source: github://oxan/esphome-stream-server
