#GPIO
# 2 = blue led
# 4 = buzzer
# 13
# 14
# 15 = zRST
# 19 = rx zigbee
# 21 = green led
# 22 = boot
# 23 = tx zigbee
# 25 = scl
# 26 = sda
# 27 = button key
# 33

substitutions:
  devicename: sonoffzbbridgep
  friendly_name: zb-bridge-p
  
packages:
  zb-bridge-p:
  url: https://github.com/Giancky79/ZB-Bridge-P
  ref: main
  files:
     - esphome/esphome.yaml
     - esphome/binary_sensor.yaml
     - esphome/light.yaml
     - esphome/output.yaml
     - esphome/rtttl.yaml
     - esphome/sensor.yaml
     - esphome/output.yaml
     - esphome/switch.yaml
     - esphome/text_sensor.yaml
     - esphome/uart.yaml
  refresh: 0s

external_components:
#  - source: github://tube0013/esphome-stream-server-v2
  - source: github://oxan/esphome-stream-server
