binary_sensor:
  
  - platform: gpio
    pin: 
      number: 27
      inverted: True
    name: "update_switch"
    internal: True
    device_class: update
    on_click:
      min_length: 1s
      max_length: 3s
      then:
        - switch.turn_on: reboot
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.turn_on: fwupdate

  - platform: stream_server
    stream_server: ss
    name: "ZBBridge-P Serial Connected"
