binary_sensor:
 
  - platform: status
    name: "${friendly_name} Status"

  - platform: gpio
    pin: 
      number: 27
      inverted: True
    name: "update_switch"
    internal: True
    device_class: update
    on_click:
      min_length: 1s
      max_length: 3s
      then:
        - button.press: reboot
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.turn_on: fw_update

  - platform: stream_server
    connected:
      name: Connected from PC
