esphome:
  name: ${devicename}
  on_boot:
    priority: 800
    then:
      - switch.turn_on: zigbee_rst
      - delay: 15ms
      - switch.turn_off: zigbee_rst
      - delay: 1s
      - light.turn_on: blue
      - delay: 1s
      - rtttl.play: 'long:d=1,o=5,b=100:e6' 

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  baud_rate: 0

api:
  reboot_timeout: 0s

ota:

captive_portal:
