esphome:
  name: ${devicename}
  on_boot:
    priority: 800
    then:
      - rtttl.play: 'long:d=1,o=5,b=100:e6'
      - delay: 4s 
      - light.turn_on: blue

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG
  baud_rate: 0

api:
  reboot_timeout: 0s

ota:
  
wifi:
  ssid: wifi_ssid
  password: wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: !secret ap_password

captive_portal:
