switch:

  - platform: template
    name: "${friendly_name} fw update"
    id: fw_update
    turn_on_action:
      - light.turn_off: blue
      - delay: 1s 
      - switch.turn_on: zigbee_bsl
      - delay: 1s
      - switch.turn_on: zigbee_rst
      - delay: 1s
      - switch.turn_off: zigbee_rst
      - delay: 2s
      - switch.turn_off: zigbee_bsl
      - delay: 1s
      - light.turn_on: green
      - rtttl.play: "long:d=1,o=5,b=100:e6"
      - logger.log: "please try to write fw on ip:6638, if a error of Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)' repeat with fw update"
      - delay: 20s
      - light.turn_off: green
      - delay: 1s
      - light.turn_on: blue
      - delay: 1s
      - switch.turn_off: fw_update
      - logger.log: "remember to reboot after update fw zigbee"

  - platform: gpio
    id: zigbee_rst
    pin: 15
    name: "Zigbee RST"
    inverted: True
    internal: True
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: zigbee_bsl
    pin: 22
    name: "Zigbee BSL"
    inverted: True
    internal: True
    restore_mode: ALWAYS_OFF
