switch:

  - platform: restart
    name: "${friendly_name} Restart"
    id: reboot 
    internal: true
    icon: "mdi:restart"

  - platform: template
    name: "${friendly_name} fw update"
    id: fwupdate
    turn_on_action:
      - light.turn_off: blue
      - delay: 1s 
      - switch.turn_on: zigbee_bsl
      - delay: 1s
      - switch.turn_on: zigbee_rst
      - delay: 1s
      - switch.turn_off: zigbee_rst
      - logger.log: "wait for fw update"
      - delay: 12s
      - light.turn_on: green
      - switch.turn_off: zigbee_bsl 
      - logger.log: "please try to write fw on ip:6638, if a error of Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)' repeat with fw update"
      - delay: 15s
      - light.turn_off: green
      - delay: 5s
      - light.turn_on: blue

  - platform: gpio
    id: zigbee_rst
    pin: 15
    name: "Zigbee RST"
    inverted: true
    internal: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: zigbee_bsl
    pin: 22
    name: "Zigbee BSL"
    inverted: False
    internal: true
    restore_mode: ALWAYS_OFF
